errors.mqtt.topic = "te/errors"

input.mqtt.topics = [
    "tbflow/device/+/+/+/m/+",
    "tbflow/device/+/+/+/twin/+",
    "tbflow/device/+/+/+/a/+",
    "tbflow/device/+/+/+/e/+",
    "tbflow/device/+/+/+/status/health"
]

[[steps]]
builtin = "add-timestamp"
config.property = "time"
config.format = "unix"
config.reformat = true

[[steps]]
script = "thingsboard/lib/main.js"

interval = "10m"
config.add_type_to_key = true
config.alarm_prefix = "alarm::"
config.event_prefix = "event::"
config.enable_heartbeat = true

