input.mqtt.topics = ["te/device/+/+/+/m/+", "te/device/+/+/+/twin/+", "te/device/+/+/+/a/+",  "te/device/+/+/+/e/+"]

[[steps]]
builtin = "add-timestamp"
config.property = "time"
config.format = "unix"
config.reformat = true

[[steps]]
script = "thingsboard/lib/main.js"
config.main_device_name = "{{MAIN_DEVICE_NAME}}"
config.add_type_to_key = true
config.alarm_prefix = "alarm::"
config.event_prefix = "event::"

errors.mqtt.topic = "te/errors"
