[input]
mqtt.topics = [
    "te/device/main/+/+/m/environment",
    "te/device/main/+/+/m/location",
    "c8y-mqtt/proto/setpoint",
]

[[steps]]
script = "protobuf-xform/lib/main.js"
# config.topic: Use the template variable, '{{type}}' if you wish to include the sensor data type within the topic
config.topic = "c8y-mqtt/proto/sensor_data"
config.cmdtopic = "te/device/main///sig/setpoint"
config.base64 = false
