[input]
mqtt.topics = [
    "azeg/DCMD/+/#",
    "te/+/+/+/+/cmd/+/+",
]

[[steps]]
script = "cloud-mapper-commands/lib/main.js"
config.cloud_prefix = "azeg"

# List of commands which should be mapped from the cloud to tedge topics
config.commands = ["writeSetpoint"]
