[input.process]
command = """sh -c \"tedge cert show | tr '\\n' '\\0'\""""
interval = "600s"

[[steps]]
script = "certificate-alert/lib/main.js"

# turn on additional debugging
config.debug = false

##############################
# alerts / alarming
##############################

# disable alarming
config.disable_alarms = false

# threshold when to create a major alarm
config.alarm = "30d"

# threshold when to create a warning
config.warning = "90d"

##############################
# certificate meta information
##############################
# don't publish digital twin data
config.disable_twin = false

# digital twin property where to publish the certificates meta information to
config.twin_property = "tedge_Certificate"
