errors.mqtt.topic = "te/errors"

[input]
mqtt.topics = [
    "tbflow/device/+/+/+/cmd/+/+",
    "tb/me/server/rpc/request/+",
    "tb/gateway/rpc"
]

[[steps]]
script = "thingsboard-server-rpc/lib/main.js"
